version: '3'
services:
  go_1.20:
    build:
      context: .
      target: dev
      dockerfile: ./conf/Dockerfile
    container_name: go-practice-container
    volumes:
      - ./src:/go/src
    ports:
      - 8080:8080
    tty: true
    